import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import Header from "./components/Header";
import { UserProvider } from "./context/UserContext";
import { Inter } from 'next/font/google'
import { Nunito } from 'next/font/google';

const inter = Inter({
    subsets: ['latin'],
    weight: ['400', '600', '700'], // tuỳ chọn các độ dày cần
    display: 'swap',
})

export const nunito = Nunito({
    subsets: ['latin'],
    weight: ['400', '600', '700'],
    display: 'swap',
    variable: '--font-ui',
});

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body suppressHydrationWarning className={`${nunito.className} ${geistMono.variable} antialiased`}>
                <UserProvider>
                    {/* <Header /> */}
                    <Providers>{children}</Providers>
                </UserProvider>
            </body>
        </html>
    );
}
